"""empty message

Revision ID: 22fd4106b37f
Revises: 
Create Date: 2025-11-23 11:51:39.741789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22fd4106b37f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_buah', schema=None) as batch_op:
        batch_op.add_column(sa.Column('harga_satuan', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_buah', schema=None) as batch_op:
        batch_op.drop_column('harga_satuan')

    # ### end Alembic commands ###
